project_id = "qaftogrqeyymewoofexc"

[functions.sitemap]
verify_jwt = false

[functions.import-rss]
verify_jwt = false

[functions.batch-optimize-images]
verify_jwt = false

[functions.push-notifications]
verify_jwt = false
